### ISSUE TITLE
Random error installing typings

### ISSUE THREAD

**Issue by juanan** [typings/grunt-typings#2]
Hi,

I'm getting a random error when trying to run the grunt-typings task: Unable to read typings for "jquery". You should check the path is correct.

Could you tell me pls why this error happens?

Each time this error ocurrs, it references a distinct ambient dependecy.

My grunt file:

```
// refreshes ts definition files
typings: {
  install: {}
},
```

My typings file:

{
  "name": "settlementdrafts",
  "ambientDependencies": {
    "angular": "github:DefinitelyTyped/DefinitelyTyped/angularjs/angular.d.ts#dade4414712ce84e3c63393f1aae407e9e7e6af7",
    "jquery": "github:DefinitelyTyped/DefinitelyTyped/jquery/jquery.d.ts#dade4414712ce84e3c63393f1aae407e9e7e6af7",
    "angular-ui-router": "github:DefinitelyTyped/DefinitelyTyped/angular-ui-router/angular-ui-router.d.ts#4910a7c52a1cf335877ea3b0917eb65117a66637",
    "angular-translate": "github:DefinitelyTyped/DefinitelyTyped/angular-translate/angular-translate.d.ts#4910a7c52a1cf335877ea3b0917eb65117a66637",
    "angular-cookies": "github:DefinitelyTyped/DefinitelyTyped/angularjs/angular-cookies.d.ts#4910a7c52a1cf335877ea3b0917eb65117a66637",
    "angular-dynamic-locale": "github:DefinitelyTyped/DefinitelyTyped/angular-dynamic-locale/angular-dynamic-locale.d.ts#4910a7c52a1cf335877ea3b0917eb65117a66637",
    "moment": "github:DefinitelyTyped/DefinitelyTyped/moment/moment.d.ts#6035d7e34a7a64902f29cacd96abfb8af10f3da1",
    "moment-node": "github:DefinitelyTyped/DefinitelyTyped/moment/moment-node.d.ts#6035d7e34a7a64902f29cacd96abfb8af10f3da1",
    "lodash": "github:DefinitelyTyped/DefinitelyTyped/lodash/lodash.d.ts#72f0056f69f9a2290d2589c1a692896d24406928",
    "angular-toastr": "github:DefinitelyTyped/DefinitelyTyped/angular-toastr/angular-toastr.d.ts#dade4414712ce84e3c63393f1aae407e9e7e6af7",
    "angular-file-upload": "github:DefinitelyTyped/DefinitelyTyped/angular-file-upload/angular-file-upload.d.ts#dade4414712ce84e3c63393f1aae407e9e7e6af7",
    "ng-file-upload": "github:DefinitelyTyped/DefinitelyTyped/ng-file-upload/ng-file-upload.d.ts#dade4414712ce84e3c63393f1aae407e9e7e6af7"
  }
}

**Comment by sebastianhaas** [comment]
Hey!
Your `typings.json` works fine for me. I set up a `Gruntfile` and `typings.json` just as you described and I was able to resolve all typings correctly.

Have you tried running `typings install` directly in your working dir? Anyway, I assume this is not really related to the grunt plugin itself.

**Comment by juanan** [comment]
Ok, I will redirect the question to the typings task.

Thanks a lot.

**Comment by sebastianhaas** [comment]
You're welcome. Feel free to reopen anytime if you need help.
